package event

const (
	// Cloud Event Types
	// Event generated by Real Twin (Real Twin -> Virtual Twin)
	EVENT_TYPE_REAL_GENERATED string = "ktwin.real.%s" // ktwin.real.<twin interface>
	// Event Generated by Virtual Twin (Virtual Twin -> Real Twin)
	EVENT_TYPE_VIRTUAL_GENERATED string = "ktwin.virtual.%s" // ktwin.virtual.<twin interface>
	// Route event to event store to be persisted. To be used by async event store persistence. (Virtual Twin -> Event Store)
	EVENT_TYPE_STORE_EXECUTED string = "ktwin.store.%s" // ktwin.store.<twin interface>
	// Invoke Virtual Twin command
	EVENT_TYPE_COMMAND_EXECUTED string = "ktwin.command.%s.%s" // ktwin.command.<twin interface>.<command>
)

const (
	// MQTT Dispatchers name
	CLOUD_EVENT_DISPATCHER = "cloud-event-dispatcher"
	MQTT_DISPATCHER        = "mqtt-dispatcher"

	// MQTT Dispatcher Queues
	CLOUD_EVENT_DISPATCHER_QUEUE string = "cloud-event-dispatcher-queue"
	MQTT_DISPATCHER_QUEUE        string = "mqtt-dispatcher-queue"
)

const (
	EVENT_BROKER_NAME               string = "ktwin"
	RABBITMQ_VHOST                  string = "/"
	CLOUD_EVENT_DISPATCHER_EXCHANGE string = "amq.topic"
	MQTT_EXCHANGE                   string = "amq.topic"
)
