{
 "title": "Serverless Metrics Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Broker Message delivery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Count /s by Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[1m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Count by Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[$__range])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Event Count / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Event Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[$__range]))",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Incoming Messages Broker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[1m]))",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Incoming Messages Broker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[$__range]))",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Success Rate  (2xx Event)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_ingress_event_count{response_code_class=\"2xx\", namespace_name=~\"ktwin\"}[1m])) / sum(rate(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[1m]))",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Failure Rate (non-2xx Event)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_ingress_event_count{response_code_class!=\"2xx\", namespace_name=~\"ktwin\"}[1m])) / sum(rate(rabbitmq_ingress_event_count{namespace_name=~\"ktwin\"}[1m])) OR on() vector(0)",
     "legendFormat": "Event count"
    }
   ]
  },
  { "title": "RabbitMQ Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queues * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_redelivered_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_auto_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_auto_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_manual_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Incoming messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_global_messages_received_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_global_messages_redelivered_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(increase(rabbitmq_global_messages_delivered_consume_auto_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(increase(rabbitmq_global_messages_delivered_consume_auto_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(increase(rabbitmq_global_messages_delivered_consume_manual_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(increase(rabbitmq_global_messages_delivered_get_auto_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(increase(rabbitmq_global_messages_delivered_get_manual_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Peak Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_redelivered_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_auto_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_auto_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\nsum(rate(rabbitmq_global_messages_delivered_get_manual_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "description": "Total number of client connections.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rabbitmq_connections * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{namespace=\"ktwin\"}",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Connections Opened / s",
   "type": "timeseries",
   "description": "Total number of client connections.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connections_opened_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{namespace=\"ktwin\"}) by(rabbitmq_node)",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "Connections Closed / s",
   "type": "timeseries",
   "description": "Total number of client connections.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connections_closed_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{namespace=\"ktwin\"}) by(rabbitmq_node)",
     "legendFormat": "Event count"
    }
   ]
  },
  {
   "title": "RabbitMQ Messages published /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) by(rabbitmq_node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Aggregated RabbitMQ Messages published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_global_messages_received_total[$__range]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) by(rabbitmq_node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(rabbitmq_global_messages_received_total[$__range]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RabbitMQ Messages delivered /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  (rate(rabbitmq_global_messages_delivered_consume_auto_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\n  (rate(rabbitmq_global_messages_delivered_consume_manual_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})\n) by(rabbitmq_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregated RabbitMQ Messages delivered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  (increase(rabbitmq_global_messages_delivered_consume_auto_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) +\n  (increase(rabbitmq_global_messages_delivered_consume_manual_ack_total[$__range]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"})\n) by(rabbitmq_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unroutable messages dropped / s",
   "type": "timeseries",
   "description": "The rate of messages that cannot be routed and are dropped. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_unroutable_dropped_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) by(rabbitmq_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unroutable messages dropped",
   "type": "timeseries",
   "description": "The rate of messages that cannot be routed and are dropped. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_global_messages_unroutable_dropped_total[$__range]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"rabbitmq\", namespace=\"ktwin\"}) by(rabbitmq_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Services Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(autoscaler_actual_pods{namespace_name=\"ktwin\"}) by (configuration_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(autoscaler_actual_pods{namespace_name=\"ktwin\"})",
     "legendFormat": "Total Number of Pods"
    }
   ]
  },
  {
   "title": "Request Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(activator_request_concurrency{namespace_name=\"ktwin\"}) by (configuration_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(activator_request_concurrency{namespace_name=\"ktwin\"})",
     "legendFormat": "Total Concurrency"
    }
   ]
  },
  {
   "title": "Request Volume / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(round(sum(rate(activator_request_count{namespace_name=\"ktwin\"}[1m])) by (revision_name), 0.001), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(rate(activator_request_count{namespace_name=\"ktwin\"}[1m])), 0.001)",
     "legendFormat": "All Revisions"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(round(sum(increase(activator_request_count{namespace_name=\"ktwin\"}[$__range])) by (revision_name), 0.001), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(increase(activator_request_count{namespace_name=\"ktwin\"}[$__range])), 0.001)",
     "legendFormat": "All Revisions"
    }
   ]
  },
  {
   "title": "Request Volume / s (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(rate(activator_request_count{namespace_name=\"ktwin\", response_code_class=\"4xx\"}[1m])) by (configuration_name), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume / s (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(rate(activator_request_count{namespace_name=\"ktwin\", response_code_class=\"2xx\"}[1m])) by (configuration_name), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume / s (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(rate(activator_request_count{namespace_name=\"ktwin\", response_code_class=\"5xx\"}[1m])) by (configuration_name), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Volume (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(activator_request_count{namespace_name=\"ktwin\", response_code_class=\"5xx\"}[$__range])) by (configuration_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate / s (5xx / ALL)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(activator_request_count{namespace_name=\"ktwin\", response_code_class=\"5xx\"}[1m])) by (configuration_name) / (sum(rate(activator_request_count{namespace_name=\"ktwin\"}[1m])) by (configuration_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Percentage (5xx / ALL)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((activator_request_count{namespace_name=\"ktwin\", response_code_class=\"5xx\"})) by (configuration_name) / (sum((activator_request_count{namespace_name=\"ktwin\"})) by (configuration_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(activator_request_latencies_bucket{namespace_name=\"ktwin\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p50)"
    }
   ]
  },
  {
   "title": "Response Time (p90)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(rate(activator_request_latencies_bucket{namespace_name=\"ktwin\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p90)"
    }
   ]
  },
  {
   "title": "Response Time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(activator_request_latencies_bucket{namespace_name=\"ktwin\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p95)"
    }
   ]
  },
  {
   "title": "Response Time (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(rate(activator_request_latencies_bucket{namespace_name=\"ktwin\"}[1m])) by (revision_name, le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "{{revision_name}} (p99)"
    }
   ]
  },
  { "title": "Resource Utillization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}[1m])) by(container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}[1m])) ",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})",
     "legendFormat": "Total Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage - Requests (core)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) ",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage - Limit (Core)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage - Requests (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})",
     "legendFormat": "Total Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Usage - Limit (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})",
     "legendFormat": "Total Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage / Requested",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round (\n  100 *\nsum (rate(container_cpu_usage_seconds_total{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}[1m])) by(container)\n/\n(\nsum (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)\n)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "round (\n  100 *\nsum (rate(container_cpu_usage_seconds_total{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}[1m]))\n/\n(\nsum (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})\n)\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage / Requested",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by (container)\n      /\n    sum(kube_pod_container_resource_requests{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\", resource=\"memory\"} > 0) by (container)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})\n      /\n    sum(kube_pod_container_resource_requests{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\", resource=\"memory\"} > 0)\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage / Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round (\n  100 *\nsum (rate(container_cpu_usage_seconds_total{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}[1m])) by(container)\n/\n(\nsum (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by(container)\n)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "round (\n  100 *\nsum (rate(container_cpu_usage_seconds_total{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}[1m]))\n/\n(\nsum (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})\n)\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage / Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"}) by (container)\n      /\n    sum(kube_pod_container_resource_limits{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\", resource=\"memory\"} > 0) by (container)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\"})\n      /\n    sum(kube_pod_container_resource_limits{namespace=\"ktwin\", container!=\"POD\", container!=\"\", container!=\"grafana\", container!=\"battery-device-publisher\", container!=\"ev-charging-device-publisher\", container!=\"parking-spot-device-publisher\", container!=\"pole-air-quality-observed-device-publisher\", container!=\"pole-noise-level-observed-device-publisher\", container!=\"pole-weather-observed-device-publisher\", container!=\"ingress\", container!=\"pole-crowd-flow-observed-device-publisher\", container!=\"pole-traffic-flow-observed-device-publisher\", container!=\"streetlight-device-publisher\", container!=\"\", resource=\"memory\"} > 0)\n)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}