# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dtd.ktwin_twininterfaces.yaml
- bases/dtd.ktwin_twininstances.yaml
- bases/core.ktwin_gateways.yaml
- bases/core.ktwin_mqtttriggers.yaml
- bases/core.ktwin_eventstores.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_twininterfaces.yaml
#- patches/webhook_in_twininstances.yaml
#- patches/webhook_in_gateways.yaml
#- patches/webhook_in_mqtttriggers.yaml
#- patches/webhook_in_eventstores.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_twininterfaces.yaml
#- patches/cainjection_in_twininstances.yaml
#- patches/cainjection_in_gateways.yaml
#- patches/cainjection_in_mqtttriggers.yaml
#- patches/cainjection_in_eventstores.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
